=== EasyinnovaSL/TIFF-Implementation-Checker/src/main/resources/implementationcheckers/ProfileChecker.xsd
<?xml version="1.0" encoding="UTF-8"?> 
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns="http://www.dpfmanager.org/ProfileChecker"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
    targetNamespace="http://www.dpfmanager.org/ProfileChecker" elementFormDefault="qualified"
    vc:minVersion="1.0" vc:maxVersion="1.1">

    <xsd:element name="implementationCheckerObject" type="implementationCheckerObjectType"/>

    <xsd:complexType name="implementationCheckerObjectType">
        <xsd:sequence>
            <xsd:element name="title" type="xsd:string" maxOccurs="1" minOccurs="1"/>
            <xsd:element name="iso" type="xsd:string" maxOccurs="1" minOccurs="1"/>
            <xsd:element name="description" type="xsd:string" maxOccurs="1" minOccurs="1"/>
            <xsd:element name="version" type="xsd:string" maxOccurs="1" minOccurs="1"/>
            <xsd:element name="author" type="xsd:string" maxOccurs="1" minOccurs="1"/>
            <xsd:element maxOccurs="1" minOccurs="1" name="date" type="xsd:date"/>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="include" type="includeType"/>
            <xsd:sequence maxOccurs="1" minOccurs="1">
                <xsd:element name="rules" maxOccurs="unbounded" minOccurs="1" type="rulesType"/>
            </xsd:sequence>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="includeType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="1" name="policyChecker" type="xsd:string"/>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="excluderules" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="rulesType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="1" name="title" type="xsd:string"/>
            <xsd:element name="description" type="xsd:string" maxOccurs="1" minOccurs="1"/>
            <xsd:element name="rule" type="ruleType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:ID" use="required"/>

    </xsd:complexType>

    <xsd:complexType name="ruleType">
        <xsd:sequence>
            <xsd:element name="title" maxOccurs="1" minOccurs="1">
                <xsd:complexType>
                    <xsd:simpleContent>
                        <xsd:extension base="xsd:string"> </xsd:extension>
                    </xsd:simpleContent>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="description" maxOccurs="1" minOccurs="1">
                <xsd:complexType>
                    <xsd:simpleContent>
                        <xsd:extension base="xsd:string"> </xsd:extension>
                    </xsd:simpleContent>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="reference" type="referenceType" minOccurs="1" maxOccurs="unbounded"/>
            <xsd:element name="assert" type="assertType" maxOccurs="1" minOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:ID" use="required"/>
        <xsd:attribute name="context" type="xsd:string" use="required"/>
        <xsd:attribute name="level" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="error"/>
                    <xsd:enumeration value="critical"/>
                    <xsd:enumeration value="warning"/>
                    <xsd:enumeration value="info"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute default="true" name="experimental" type="xsd:boolean" use="optional"/>
    </xsd:complexType>


    <xsd:complexType name="referenceType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="0" name="document" type="xsd:string"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="section" type="xsd:string"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="paragraph" type="xsd:string"/>
            <xsd:choice>
                <xsd:element minOccurs="1" name="page" type="xsd:string"/>
                <xsd:element maxOccurs="1" minOccurs="1" name="pages" type="xsd:string"/>
            </xsd:choice>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="assertType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="test" type="xsd:string"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

</xsd:schema>

=== EasyinnovaSL/TIFF-Implementation-Checker/src/main/resources/implementationcheckers/TIAProfileChecker.xml
<?xml version="1.0" encoding="UTF-8"?>
<implementationCheckerObject xmlns="http://www.dpfmanager.org/ProfileChecker"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.dpfmanager.org/ProfileChecker ProfileChecker.xsd">

    <title>TI/A Draft</title>
    <iso>TI/A Draft v0.1</iso>
    <description>TI/A v0.1 Draft - October 18, 2016</description>
    <version>1.0.0</version>
    <author>Easy Innova</author>
    <date>2016-10-24</date>

    <include>
        <policyChecker>TIFF_Baseline_Core_6_0.xml</policyChecker>
    </include>

    <rules id="MASTER">
        <title>Rules to validate IFD Master Image</title>
        <description>The following rules validate a valid ifd storing a master image according to TI/A specifications</description>
        <rule id="MASTER-0001" context="ifd[thumbnail=0]" level="error">
            <title>Square aspect ration</title>
            <description>In TI/A the only valid pixel aspect ratio is 1:1 (square), so that XResolution equals YResolution</description>
            <reference><document>TI/A Draft v0.1</document>
                <section>Section 4.2: Image data</section>
                <page>12</page>
            </reference>
            <assert test="{tags.tag[name=XResolution] == tags.tag[name=YResolution]}">In TI/A the only valid pixel aspect ratio is 1:1 (square)</assert>
        </rule>
        <rule id="MASTER-0002" context="ifd[thumbnail=0]" level="error">
            <title>Strip data Structure</title>
            <description>The image data is stored using strips, which are collectively termed segments.
                The following tag-fields define the number of strips and the number of rows of image data stored in each strip: StripOffsets, RowsPerStrip, and StripByteCounts.
                The image shall be divided into an integral number of strips, from 1 strip to the maximum number of strips, which equals the imageâ€™s length.
                If necessary, the final strip can be "padded" with zeros. </description>
            <reference><document>TI/A Draft v0.1</document>
                <section>Section 4.2: Image data</section>
                <page>12</page>
            </reference>
            <assert test="{strips == 1}">In TI/A the only data structure supported are strips</assert>
        </rule>
        <rule id="MASTER-0003" context="ifd[class=image]" level="warning" experimental="true">
            <title>64 Kbytes per strip</title>
            <description>It is recommended that the image data, prior to compression, not exceed 64 Kbytes per strip.
                This value is chosen to maximize compatibility with various operating systems.</description>
            <reference><document>TI/A Draft v0.1</document>
                <section>Section 4.2: Image data</section>
                <page>12</page>
            </reference>
            <assert test="{tags.tag[name=Compression] != 0} || {StripsSize &gt; 65536}">It is recommended that the image data, prior to compression, not exceed 64 Kbytes per strip.</assert>
        </rule>
        <rule id="MASTER-0004" context="ifd[thumbnail=0]" level="error">
            <title>NewSubFileType defined</title>
            <description>New NewSubFileType tag must be explicit defined in an Image File Directory storing a master image.</description>
            <reference><document>TI/A Draft v0.1</document>
                <section>Section 4.2: Image data</section>
                <page>12</page>
            </reference>
            <assert test="{tags.tag[name=NewSubfileType]}">New NewSubFileType tag must be explicitly defined in an Image File Directory storing a master image.</assert>
        </rule>
        <rule id="MASTER-0005" context="ifd[thumbnail=0]" level="error">
            <title>Valid NewSubFileType</title>
            <description>NewSubFileType tag must define a full resolution image in an Image File Directory storing a master image.</description>
            <reference><document>TI/A Draft v0.1</document>
                <section>Section 4.2: Image data</section>
                <page>12</page>
            </reference>
            <assert test="{tags.tag[name=NewSubfileType] % 2 == 0}">NewSubFileType invalid value for a master image, the value should define a full resolution image.</assert>
        </rule>
        <rule id="MASTER-0006" context="ifd[thumbnail=0]" level="error">
            <title>valid NewSubFileType</title>
            <description>TI/A standard TIFF defines a unique valid value for NewSubFileType, the value should be 0 for a full resolution image.</description>
            <reference><document>TI/A Draft v0.1</document>
                <section>Section 4.2: Image data</section>
                <page>12</page>
            </reference>
            <assert test="{tags.tag[name=NewSubfileType] == 0}"> NewSubFileType invalid values, the value should be 0 for a full resolution image</assert>
        </rule>
        <rule id="MASTER-0007" context="ifd[thumbnail=0]" level="error">
            <title>SubIFD not permitted</title>
            <description>TI/A do not permit the use of SubIFDs in a master image.</description>
            <reference><document>TI/A Draft v0.1</document>
                <section>Section 4.2: Image data</section>
                <page>12</page>
            </reference>
            <assert test="{count(tags.tag[name=SubIFDs]) == 0}">TI/A do not permit the use of SubIFDs in a master image</assert>
        </rule>
       
        <rule id="MASTER-0009" context="ifd[thumbnail=0]" level="error">
            <title>Master image with a subIFD thumbnail</title>
            <description>Although TI/A do not recommend the use of thumbnails, when a thumbnails is defined it must contain a subIFD containing the main image.</description>
            <reference><document>TI/A Draft v0.1</document>
                <section>Section 4.2: Image data</section>
                <page>12</page>
            </reference>
            <assert test="{tags.tag[name=SubIFDs].ifd.tags.tag[name=NewSubfileType] % 2 == 0}">Invalid IFD structure,The Master image define a subIFD containing a thumbnail</assert>
        </rule>

        <rule id="MASTER-0010" context="ifd[thumbnail=0]" level="warning">
            <title>Master image recommended compression</title>
            <description>TI/A do not recommend the use of compression for storing a master images, An uncompressed image is always the best option for archival purpose</description>
            <reference><document>TI/A Draft v0.1</document>
                <section>Section 4.2: Image data</section>
                <page>12</page>
            </reference>
            <assert test="{tags.tag[name=Compression]!=1}">TI/A do not recommend the use of compression for storing a master images, an uncompressed image is preferred for archival purpose</assert>
        </rule>
        <rule id="MASTER-0011" context="ifd[thumbnail=0]" level="error">
            <title>CCITT 1D compression</title>
            <description>CCITT 1D compression is not widely used for archival purpose, therefore obsolete</description>
            <reference><document>TI/A Draft v0.1</document>
                <section>Section 4.2: Image data</section>
                <page>12</page>
            </reference>
            <assert test="{tags.tag[name=Compression]!=2}">CCITT 1D Compression is forbidden regarding the TI/A the specification</assert>
        </rule>
        <rule id="MASTER-0012" context="ifd[thumbnail=0]" level="error">
            <title>Group 3 Fax compression</title>
            <description>Group 3 Fax compression is not widely used for archival purpose, therefore obsolete</description>
            <reference><document>TI/A Draft v0.1</document>
                <section>Section 4.2: Image data</section>
                <page>12</page>
            </reference>
            <assert test="{tags.tag[name=Compression]!=3}">Group 3 Fax Compression is forbidden regarding the TI/A the specification</assert>
        </rule>
        <rule id="MASTER-0013" context="ifd[thumbnail=0]" level="warning">
            <title>Group 4 Fax compression</title>
            <description>Although Group 4 Fax compression is supported in TI/A, is not recommended</description>
            <reference><document>TI/A Draft v0.1</document>
                <section>Section 4.2: Image data</section>
                <page>12</page>
            </reference>
            <assert test="{tags.tag[name=Compression]==4}">Group 4 Fax compression is supported in TI/A but not recommended</assert>
        </rule>
        <rule id="MASTER-0014" context="ifd[thumbnail=0]" level="warning">
            <title>LZW compression</title>
            <description>LZW compression is supported in TI/A specifications but not recommended</description>
            <reference><document>TI/A Draft v0.1</document>
                <section>Section 4.2: Image data</section>
                <page>12</page>
            </reference>
            <assert test="{tags.tag[name=Compression]==5}">LZW compression is supported in TI/A but not recommended</assert>
        </rule>
        <rule id="MASTER-0015" context="ifd[thumbnail=0]" level="error">
            <title>Main image JPEG TIFF/6-.0 compression</title>
            <description>JPEG 'old' compression is replaced by 'new JPEG' and not widely used for archival purpose, therefore obsoleted</description>
            <reference><document>TI/A Draft v0.1</document>
                <section>Section 4.2: Image data</section>
                <page>12</page>
            </reference>
            <assert test="{tags.tag[name=Compression]!=6}">JPEG TIFF/6-.0 'old JPEG' Compression is forbidden regarding the TI/A the specification</assert>
        </rule>
        <rule id="MASTER-0016" context="ifd[thumbnail=0]" level="warning">
            <title>Main image JPEG TIFF TechNote2 compression</title>
